# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Maxlaptop::Admin
    #description:  symfony project
    #keywords:     symfony, project
    language:     fa
    #robots:       index, follow

  stylesheets:    [main.css, style.css, smoothness/jquery-ui-1.8.16.custom.css]

  javascripts:    [jquery.js, script.js, jquery-ui-1.8.16.custom.min.js]

  has_layout:     true
  layout:         layout
