generator:
  class: sfPropelGenerator
  param:
    model_class:           Page
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:    Pages
        layout:   stacked
        display:  [=title, parent_id, summary, is_published, updated_at]
        params:   |
                  <table><tr><td><table><tr><td><b>%%parent%% > %%title%% </b> [<small>%%updated_at%%</small>]</td></tr><tr><td><em>%%summary%%</em></td></tr></table></td><td>%%is_published%%</td></tr></table>
        max_per_page: 10
        batch_actions:
           _delete:    ~
           publish:    ~
           draft:      ~
        object_actions:
           publish:    ~
           _edit:      ~
           _delete:    ~
      filter:
          display: [title, parent_id, keywords, content, is_published]
      form:     ~
      edit:
        title: Edit Page: %%title%%
      new:
        title: New Page  
